# Generated by Django 4.2.13 on 2024-06-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(db_index=True)),
                ('device_name', models.CharField(max_length=100)),
                ('device_serial_number', models.UUIDField(db_index=True)),
                ('device_timestamp', models.DateTimeField(db_index=True)),
                ('recording_type', models.CharField(choices=[('history', 'History'), ('scan', 'Scan')], db_index=True, max_length=15)),
                ('glucose_history_mg_dl', models.IntegerField(blank=True, null=True)),
                ('glucose_scan_mg_dl', models.IntegerField(blank=True, null=True)),
                ('fast_acting_insulin', models.CharField(blank=True, max_length=100, null=True)),
                ('fast_acting_insulin_units', models.FloatField(blank=True, null=True)),
                ('food_data', models.CharField(blank=True, max_length=100, null=True)),
                ('carbohydrates_grams', models.FloatField(blank=True, null=True)),
                ('carbohydrates_servings', models.FloatField(blank=True, null=True)),
                ('long_acting_insulin', models.CharField(blank=True, max_length=100, null=True)),
                ('long_acting_insulin_units', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('glucose_test_strip_mg_dl', models.IntegerField(blank=True, null=True)),
                ('ketone_mmol_l', models.FloatField(blank=True, null=True)),
                ('meal_insulin_units', models.FloatField(blank=True, null=True)),
                ('correction_insulin_units', models.FloatField(blank=True, null=True)),
                ('user_adjusted_insulin_units', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
